Force node to use CJS to get around dependency import errors
Should resolve https://github.com/sjdemartini/mui-tiptap/issues/256.

Both `@mui/icons-material`
(https://github.com/mui/material-ui/issues/35233) and `lodash`
(https://github.com/lodash/lodash/issues/5107) have problems being
imported in a consuming package when using ESM. The workarounds
attempted in https://github.com/sjdemartini/mui-tiptap/pull/258 almost
seemed to work (didn't break a downstream bundled package using Vite),
but still caused problems for the original example node application
https://codesandbox.io/p/devbox/pensive-volhard-hyhtls, with errors
like:

```
Error: Cannot find module '/path/to/mui-tiptap-in-node/node_modules/@mui/icons-material/esm/FormatColorFill
```

This approach is inspired by what tss-react does
https://github.com/garronej/tss-react/blob/f5351e42e33f35f18415cfc1ffc6b08eb8ce4d25/package.json
(e.g. see here
https://github.com/garronej/tss-react/commit/46997026db70ec9bc326a1405d1ab7ea99a8d111
and https://github.com/garronej/tss-react/issues/164).

With this change, this code now works in the node context (though
slightly odd):

```
import pkg from "mui-tiptap";
const { FontSize, HeadingWithAnchor, ResizableImage, TableImproved } = pkg;
```